// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: id_counter.sql

package sqlc

import (
	"context"
)

const getNextCounter = `-- name: GetNextCounter :one
UPDATE id_counter SET counter = counter + 1, updated_at = now()
WHERE id = 'global'
RETURNING counter
`

func (q *Queries) GetNextCounter(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getNextCounter)
	var counter int64
	err := row.Scan(&counter)
	return counter, err
}
