// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type IDCounter struct {
	ID        string    `json:"id"`
	Counter   int64     `json:"counter"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Table for storing notes with public/private mode
type Note struct {
	ID string `json:"id"`
	// public: plaintext, private: nonce||ciphertext AES-GCM
	Mode string `json:"mode"`
	// plaintext for public, nonce||ciphertext for private
	Content []byte `json:"content"`
	// 16 byte random salt for private mode, empty for public
	Salt  []byte `json:"salt"`
	Title string `json:"title"`
	// true jika note diproteksi password untuk akses edit/delete
	IsViewOnly bool `json:"is_view_only"`
	// Hash password (bcrypt/argon2) untuk otorisasi pengeditan
	EditPasswordHash pgtype.Text `json:"edit_password_hash"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type NoteAttachment struct {
	ID     string `json:"id"`
	NoteID string `json:"note_id"`
	// Index sequential per note, dimulai dari 1 (lihat GetNextAttachmentIndex)
	AttachmentIndex int32 `json:"attachment_index"`
	// key object di R2. Untuk attachment private, isinya adalah nonce||ciphertext AES-GCM (application/octet-stream)
	R2Key       string `json:"r2_key"`
	Url         string `json:"url"`
	ContentType string `json:"content_type"`
	FileSize    int64  `json:"file_size"`
	Kind        string `json:"kind"`
	// true jika note pemiliknya mode private — content_type & file_size di sini merujuk ke file ASLI (sebelum dienkripsi), bukan blob terenkripsi di R2
	Encrypted bool      `json:"encrypted"`
	CreatedAt time.Time `json:"created_at"`
}
