// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type IDCounter struct {
	ID        string    `json:"id"`
	Counter   int64     `json:"counter"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Table for storing notes with public/private mode
type Note struct {
	ID string `json:"id"`
	// public: plaintext, private: nonce||ciphertext AES-GCM
	Mode string `json:"mode"`
	// plaintext for public, nonce||ciphertext for private
	Content []byte `json:"content"`
	// 16 byte random salt for private mode, empty for public
	Salt      []byte    `json:"salt"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type NoteAttachment struct {
	ID     string `json:"id"`
	NoteID string `json:"note_id"`
	// key object di R2. Untuk attachment private, isinya adalah nonce||ciphertext AES-GCM (application/octet-stream)
	R2Key       string `json:"r2_key"`
	Url         string `json:"url"`
	ContentType string `json:"content_type"`
	FileSize    int64  `json:"file_size"`
	Kind        string `json:"kind"`
	// true jika note pemiliknya mode private — content_type & file_size di sini merujuk ke file ASLI (sebelum dienkripsi), bukan blob terenkripsi di R2
	Encrypted bool      `json:"encrypted"`
	CreatedAt time.Time `json:"created_at"`
}
