// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package sqlc

import (
	"context"
)

const countNotes = `-- name: CountNotes :one
SELECT COUNT(*) FROM notes
`

func (q *Queries) CountNotes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNotes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNote = `-- name: CreateNote :one
INSERT INTO notes (id, mode, content, salt, title)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, mode, content, salt, title, created_at, updated_at
`

type CreateNoteParams struct {
	ID      string `json:"id"`
	Mode    string `json:"mode"`
	Content []byte `json:"content"`
	Salt    []byte `json:"salt"`
	Title   string `json:"title"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.ID,
		arg.Mode,
		arg.Content,
		arg.Salt,
		arg.Title,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.Content,
		&i.Salt,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :execrows
DELETE FROM notes WHERE id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNote, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNote = `-- name: GetNote :one
SELECT id, mode, content, salt, title, created_at, updated_at FROM notes WHERE id = $1
`

func (q *Queries) GetNote(ctx context.Context, id string) (Note, error) {
	row := q.db.QueryRow(ctx, getNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.Content,
		&i.Salt,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNoteContent = `-- name: UpdateNoteContent :one
UPDATE notes
SET content = $2, title = $3, updated_at = now()
WHERE id = $1
RETURNING id, mode, content, salt, title, created_at, updated_at
`

type UpdateNoteContentParams struct {
	ID      string `json:"id"`
	Content []byte `json:"content"`
	Title   string `json:"title"`
}

func (q *Queries) UpdateNoteContent(ctx context.Context, arg UpdateNoteContentParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNoteContent, arg.ID, arg.Content, arg.Title)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.Content,
		&i.Salt,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
