// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: note_attachments.sql

package sqlc

import (
	"context"
)

const countAttachmentsByNote = `-- name: CountAttachmentsByNote :one
SELECT COUNT(*) FROM note_attachments WHERE note_id = $1
`

func (q *Queries) CountAttachmentsByNote(ctx context.Context, noteID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAttachmentsByNote, noteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO note_attachments (id, note_id, attachment_index, r2_key, url, content_type, file_size, kind, encrypted)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, note_id, attachment_index, r2_key, url, content_type, file_size, kind, encrypted, created_at
`

type CreateAttachmentParams struct {
	ID              string `json:"id"`
	NoteID          string `json:"note_id"`
	AttachmentIndex int32  `json:"attachment_index"`
	R2Key           string `json:"r2_key"`
	Url             string `json:"url"`
	ContentType     string `json:"content_type"`
	FileSize        int64  `json:"file_size"`
	Kind            string `json:"kind"`
	Encrypted       bool   `json:"encrypted"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (NoteAttachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ID,
		arg.NoteID,
		arg.AttachmentIndex,
		arg.R2Key,
		arg.Url,
		arg.ContentType,
		arg.FileSize,
		arg.Kind,
		arg.Encrypted,
	)
	var i NoteAttachment
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.AttachmentIndex,
		&i.R2Key,
		&i.Url,
		&i.ContentType,
		&i.FileSize,
		&i.Kind,
		&i.Encrypted,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :execrows
DELETE FROM note_attachments
WHERE note_id = $1 AND attachment_index = $2
`

type DeleteAttachmentParams struct {
	NoteID          string `json:"note_id"`
	AttachmentIndex int32  `json:"attachment_index"`
}

func (q *Queries) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAttachment, arg.NoteID, arg.AttachmentIndex)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAttachmentsByNote = `-- name: DeleteAttachmentsByNote :exec
DELETE FROM note_attachments WHERE note_id = $1
`

func (q *Queries) DeleteAttachmentsByNote(ctx context.Context, noteID string) error {
	_, err := q.db.Exec(ctx, deleteAttachmentsByNote, noteID)
	return err
}

const getAttachmentByNoteAndIndex = `-- name: GetAttachmentByNoteAndIndex :one
SELECT id, note_id, attachment_index, r2_key, url, content_type, file_size, kind, encrypted, created_at FROM note_attachments
WHERE note_id = $1 AND attachment_index = $2
`

type GetAttachmentByNoteAndIndexParams struct {
	NoteID          string `json:"note_id"`
	AttachmentIndex int32  `json:"attachment_index"`
}

func (q *Queries) GetAttachmentByNoteAndIndex(ctx context.Context, arg GetAttachmentByNoteAndIndexParams) (NoteAttachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByNoteAndIndex, arg.NoteID, arg.AttachmentIndex)
	var i NoteAttachment
	err := row.Scan(
		&i.ID,
		&i.NoteID,
		&i.AttachmentIndex,
		&i.R2Key,
		&i.Url,
		&i.ContentType,
		&i.FileSize,
		&i.Kind,
		&i.Encrypted,
		&i.CreatedAt,
	)
	return i, err
}

const getNextAttachmentIndex = `-- name: GetNextAttachmentIndex :one
SELECT COALESCE(MAX(attachment_index), 0) + 1
FROM note_attachments
WHERE note_id = $1
`

func (q *Queries) GetNextAttachmentIndex(ctx context.Context, noteID string) (int32, error) {
	row := q.db.QueryRow(ctx, getNextAttachmentIndex, noteID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listAttachmentsByNote = `-- name: ListAttachmentsByNote :many
SELECT id, note_id, attachment_index, r2_key, url, content_type, file_size, kind, encrypted, created_at FROM note_attachments
WHERE note_id = $1
ORDER BY attachment_index ASC
`

func (q *Queries) ListAttachmentsByNote(ctx context.Context, noteID string) ([]NoteAttachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByNote, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NoteAttachment
	for rows.Next() {
		var i NoteAttachment
		if err := rows.Scan(
			&i.ID,
			&i.NoteID,
			&i.AttachmentIndex,
			&i.R2Key,
			&i.Url,
			&i.ContentType,
			&i.FileSize,
			&i.Kind,
			&i.Encrypted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
