// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CountAttachmentsByNote(ctx context.Context, noteID string) (int64, error)
	CountNotes(ctx context.Context) (int64, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (NoteAttachment, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	DeleteAttachment(ctx context.Context, id string) (int64, error)
	DeleteAttachmentsByNote(ctx context.Context, noteID string) error
	DeleteNote(ctx context.Context, id string) (int64, error)
	GetAttachmentByID(ctx context.Context, id string) (NoteAttachment, error)
	GetNextCounter(ctx context.Context) (int64, error)
	GetNote(ctx context.Context, id string) (Note, error)
	ListAttachmentsByNote(ctx context.Context, noteID string) ([]NoteAttachment, error)
	UpdateNoteContent(ctx context.Context, arg UpdateNoteContentParams) (Note, error)
}

var _ Querier = (*Queries)(nil)
